[project]
org-name = "ballerinax"
version = "0.99.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["sheets", "google", "spreadsheet"]
repository = "https://github.com/ballerina-platform/module-googlespreadsheet"
