[package]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.6"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["sheets", "google", "spreadsheet"]
repository = "https://github.com/ballerina-platform/module-googlespreadsheet"
