[package]
distribution = "2201.2.0"
org = "ballerinax"
name = "googleapis.sheets"
version = "3.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Spreadsheets", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-googlespreadsheet"
