[package]
org = "ballerinax"
name = "googleapis.sheets"
version = "0.99.8"
export= ["googleapis.sheets", "googleapis.sheets.listener"]
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["sheets", "google", "spreadsheet"]
repository = "https://github.com/ballerina-platform/module-googlespreadsheet"


[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.99.8.jar"
groupId = "org.ballerinalang.googleapis.sheets"
artifactId = "java-wrapper"
version = "0.99.8"